services:
  - type: web
    name: marhas-frontend
    branch: main
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
